export { PROTOCOL_VERSION, PROTOCOL_NAME, MIN_COMPATIBLE_PROTOCOL_VERSION, isCompatibleProtocolVersion } from './version.js';
export {
  ERROR_CODES,
  ERROR_HTTP_STATUS,
  ProtocolError,
  isErrorCode,
  protocolErrorBody,
  type ErrorCode,
  type ProtocolErrorBody,
} from './errors.js';
export {
  USER_ROLES,
  VIEWER_KINDS,
  SCOPED_TOKEN_KINDS,
  CAPABILITIES,
  READ_ONLY_VIEWERS,
  type UserRole,
  type ViewerKind,
  type ScopedTokenKind,
  type Capability,
} from './roles.js';
export {
  GRID_MODES,
  TOKEN_VISIBILITY,
  TOKEN_DISPOSITIONS,
  DOOR_STATES,
  SCENE_STATUSES,
  INSTANCE_STATUSES,
  FOG_OPS,
  FOG_SHAPES,
  ANNOTATION_KINDS,
  TEMPLATE_KINDS,
  PRESET_STEP_STATUSES,
  RUNDOWN_STATES,
  type GridMode,
  type TokenVisibility,
  type TokenDisposition,
  type DoorState,
  type SceneStatus,
  type InstanceStatus,
  type FogOpKind,
  type FogShape,
  type AnnotationKind,
  type TemplateKind,
  type PresetStepStatus,
  type RundownState,
  type Point,
  type Size,
  type Rect,
  type GridConfig,
  type AssetMetadata,
  type AssetVariant,
  type TokenRecord,
  type AuraRecord,
  type VisionConfig,
  type WallRecord,
  type DoorRecord,
  type LightRecord,
  type FogOperation,
  type AnnotationRecord,
  type TemplateRecord,
  type TerrainRecord,
  type CameraState,
  type CameraPreset,
  type LayerRecord,
  type SceneDocument,
  type ActorContext,
  type RulesAdapterInfo,
} from './types.js';
export {
  VTT_COMMAND_TYPES,
  parseCommandEnvelope,
  isVttCommandType,
  commandResultSchema,
  type VttCommandType,
  type CommandEnvelope,
} from './commands.js';
export {
  VTT_EVENT_TYPES,
  parseDurableEvent,
  type VttEventType,
  type DurableEvent,
  type EphemeralEvent,
} from './events.js';
export type { ProjectedLiveScene, VttSnapshot, ReplayFrame } from './snapshot.js';
export {
  isRecord,
  requireRecord,
  requireString,
  requireFiniteNumber,
  requireInteger,
  requireBoolean,
  requireEnum,
  requireProtocolVersion,
  optionalString,
  optionalBoolean,
  optionalFiniteNumber,
} from './validate.js';
